-- 사업설명서 공유 업로드·매칭 테이블

CREATE TABLE TB_BIZDESC_FILE (
    BIZDESC_FILE_ID   VARCHAR(20)  NOT NULL,
    FIS_YEAR          CHAR(4)      NOT NULL,
    BGT_DGR           INTEGER,
    REPORT_CD         VARCHAR(5)   NOT NULL,
    OFFICE_CD         VARCHAR(10),
    OFFICE_NM         VARCHAR(200),
    ATCH_FILE_ID      VARCHAR(20),
    ORG_FILE_NM       VARCHAR(500),
    STRE_FILE_NM      VARCHAR(200),
    FILE_STRE_COURS   VARCHAR(500),
    PARSE_JSON_PATH   VARCHAR(500),
    BIZ_COUNT         INTEGER      DEFAULT 0,
    REGI_ID           VARCHAR(20),
    REGI_DATE         DATETIME,
    MODI_ID           VARCHAR(20),
    MODI_DATE         DATETIME,
    CONSTRAINT PK_TB_BIZDESC_FILE PRIMARY KEY (BIZDESC_FILE_ID)
);

CREATE TABLE TB_BIZDESC_MATCH (
    FIS_YEAR          CHAR(4)      NOT NULL,
    BGT_DGR           INTEGER      NOT NULL,
    REPORT_CD         VARCHAR(5)   NOT NULL,
    TE_BGT_COMPO_ID   CHAR(11)     NOT NULL,
    BIZDESC_FILE_ID   VARCHAR(20)  NOT NULL,
    BIZ_SEQ           INTEGER      NOT NULL,
    BIZ_NM            VARCHAR(500),
    DEPT_NM           VARCHAR(200),
    MATCH_SCORE       NUMERIC(8,3),
    REGI_ID           VARCHAR(20),
    REGI_DATE         DATETIME,
    CONSTRAINT PK_TB_BIZDESC_MATCH PRIMARY KEY (FIS_YEAR, BGT_DGR, REPORT_CD, TE_BGT_COMPO_ID)
);
