-- 투자심사조서 조회용 뷰 (로컬 DB 누락분)
-- TB_REPORT020_D(구군별 check_yn) → 구군코드별 CHECK_YN_xxxxxx 컬럼 피벗
-- ReportWrite020.xml 의 VW_REPORT020_D 조인 전제

DROP VIEW IF EXISTS VW_REPORT020_D;

CREATE VIEW VW_REPORT020_D AS
SELECT E.REPORT_CD AS REPORT_CD
     , E.REPORT_DETL_CD AS REPORT_DETL_CD
     , E.FIS_YEAR AS FIS_YEAR
     , E.BGT_DGR AS BGT_DGR
     , E.TE_BGT_COMPO_ID AS TE_BGT_COMPO_ID
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3250000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3250000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3260000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3260000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3270000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3270000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3280000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3280000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3290000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3290000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3300000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3300000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3310000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3310000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3320000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3320000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3330000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3330000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3340000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3340000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3350000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3350000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3360000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3360000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3370000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3370000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3380000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3380000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3390000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3390000
     , MAX(CASE WHEN D.LOCAL_GOV_CD = '3400000' THEN NVL(D.CHECK_YN, 'N') ELSE 'N' END) AS CHECK_YN_3400000
  FROM TB_REPORT020 E
  LEFT OUTER JOIN TB_REPORT020_D D
    ON D.REPORT_CD = E.REPORT_CD
   AND D.REPORT_DETL_CD = E.REPORT_DETL_CD
   AND D.FIS_YEAR = E.FIS_YEAR
   AND D.BGT_DGR = E.BGT_DGR
   AND D.TE_BGT_COMPO_ID = E.TE_BGT_COMPO_ID
 GROUP BY E.REPORT_CD
        , E.REPORT_DETL_CD
        , E.FIS_YEAR
        , E.BGT_DGR
        , E.TE_BGT_COMPO_ID;
